LENGTH: 1.0
TOTAL_TIME: 1.0
N_POINTS_X: 5
N_POINTS_T: 5
LAYERS: 2
NEURONS_PER_LAYER: 10
EPOCHS: 5
KAN_EPOCHS: 5
LEARNING_RATE: 0.01
KAN_LEARNING_RATE: 0.01
RPINN: 0
EXAMPLE: 1
EPSILON: 0.01
ACTIVATION: "tanh"
OUTPUT_DIR: "test/output"
DEBUG: false
